_defaults_linux: &defaults_linux
  os: linux
  sudo: required
  services: docker
  language: generic
  dist: trusty
  cache:
    directories:
      - _ci_cache

_defaults_osx: &defaults_osx
  os: osx
  osx_image: xcode7.3
  language: generic
  cache:
    directories:
      - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - env: PYTHON=python2.7 DOCKERIMAGE="64"
      <<: *defaults_linux
    - env: PYTHON=python2.7 DOCKERIMAGE="32"
      <<: *defaults_linux
    - env: PYTHON=python3.4 DOCKERIMAGE="64"
      <<: *defaults_linux
    - env: PYTHON=python3.4 DOCKERIMAGE="32"
      <<: *defaults_linux
    - env: PYTHON=python3.5 DOCKERIMAGE="64"
      <<: *defaults_linux
    - env: PYTHON=python3.5 DOCKERIMAGE="32"
      <<: *defaults_linux
    - env: PYTHON=python3.6 DOCKERIMAGE="64"
      <<: *defaults_linux
    - env: PYTHON=python3.6 DOCKERIMAGE="32"
      <<: *defaults_linux
    - env: PYTHON="python2"
      <<: *defaults_osx
    - env: PYTHON="python3"
      <<: *defaults_osx

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash -x test-linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then bash -x test-osx.sh; fi
