cache:
  directories:
    - _ci_cache

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      language: generic
      dist: trusty
      env: PYTHON=python2.7 DOCKERFILE="Dockerfile.64"
    - os: linux
      sudo: required
      services: docker
      language: generic
      dist: trusty
      env: PYTHON=python2.7 DOCKERFILE="Dockerfile.32"
    - os: linux
      sudo: required
      services: docker
      language: generic
      dist: trusty
      env: PYTHON=python3.4 DOCKERFILE="Dockerfile.64"
    - os: linux
      sudo: required
      services: docker
      language: generic
      dist: trusty
      env: PYTHON=python3.4 DOCKERFILE="Dockerfile.32"
    - os: linux
      sudo: required
      services: docker
      language: generic
      dist: trusty
      env: PYTHON=python3.5 DOCKERFILE="Dockerfile.64"
    - os: linux
      sudo: required
      services: docker
      language: generic
      dist: trusty
      env: PYTHON=python3.5 DOCKERFILE="Dockerfile.32"
    - os: linux
      sudo: required
      services: docker
      language: generic
      dist: trusty
      env: PYTHON=python3.6 DOCKERFILE="Dockerfile.64"
    - os: linux
      sudo: required
      services: docker
      language: generic
      dist: trusty
      env: PYTHON=python3.6 DOCKERFILE="Dockerfile.32"
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: PYTHON="python2"
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: PYTHON="python3"

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash -x test-linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then bash -x test-osx.sh; fi
